### PR TITLE
Remove trailing ' from option column

### PR DESCRIPTION
**Pull request by lacostej**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Good idea, but I don't like the style, maybe something like
```ruby
current.split(" '").each { |a| a.gsub!("'", "") }
```
I haven't tested it, but that should look a bit nicer :+1:

**Comment by lacostej** [comment]
Maybe something more explicit ?

**Comment by lacostej** [comment]
The same without the unnecessary backslash...

**Comment by KrauseFx** [comment]
Great, thanks @lacostej :+1:

**Pull request merged**
