### PR TITLE
Add newer versions of Ruby for Travis

### PR DESCRIPTION
**Pull request by samnung**
I've noticed that you tried to add these Rubies for Travis in past but it didn't work well, I think the problem was only with not installed bundler.

### CODE REVIEW

**Comment by KrauseFx** [comment]
The build was successful before: https://travis-ci.org/fastlane/gym/builds/84769284, but yah, I should add the different linux versions, just like for all the other repos.

**Comment by KrauseFx** [comment]
What is the 
```
+  - gem update --system
+  - gem install bundler
``` 

for?

**Comment by KrauseFx** [comment]
Mh, interesting, I added more ruby versions and it's failing: https://travis-ci.org/fastlane/fastlane_core/jobs/84836884

So, the bundler is the thing that's missing?

**Comment by samnung** [comment]
I meant this build https://travis-ci.org/fastlane/gym/jobs/84017100, it was complaining about missing bundle command, so I tried to fix it by adding `gem install bundler`. Also bundler's gem command is adding this line to `.travis.yml`. See this:

```yaml
language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6
```

which is output from these commands:

```sh
bundle gem abc
cat abc/.travis.yml
```

Build you mentioned is only testing on Ruby 2.0.0.

**Comment by KrauseFx** [comment]
Sorry, I caused a merge conflict now, do you want to update the pull request to do the gem install bundle?

**Comment by samnung** [comment]
I think you will be faster, just close this request and copy the `before_install` lines.

**Comment by samnung** [comment]
And the latest versions of Ruby are 2.1.7 and 2.2.3 :wink:

**Comment by KrauseFx** [comment]
Thanks :+1:

**Pull request closed without merging**
