### PR TITLE
Generate xcodebuild.log for more details

### PR DESCRIPTION
**Pull request by xfreebird**
Create xcodebuild.log file containing detailed xcodebuild output.
This is very useful for debugging.
The implementation is simple, it creates xcodebuild-SchemeName.log file.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Wow, I love this, I didn't know this is possible! :+1: 

- So this will store the original `xcodebuild` output in the file, not the `xcpretty` one, right?
- We might not want to store the file in the current directory. Maybe a temporary path like `~/Library/Logs`, so you could immediately find the file using the `Console` app

Thanks for the pull request, this is great! :rocket:

**Comment by xfreebird** [comment]
Glad to hear that :+1: 

> So this will store the original xcodebuild output in the file, not the xcpretty one, right?

Yes, only the xcodebuild output.


> We might not want to store the file in the current directory. Maybe a temporary path like ~/Library/Logs, so you could immediately find the file using the Console app

From the CI (e.g. Jenkins) perspective it is easier to investigate the ```xcodebuild.log``` directly from the workspace. Also there might be file name collisions when multiple builds are started for the same project. 

What do you think ?

**Comment by xfreebird** [comment]
Also in this case xcodebuild.log could be used for OCLint.

**Comment by KrauseFx** [comment]
Sorry, we can't just put this into the working directory, but instead store it somewhere else. I'll take over this pull request, thanks again :+1:

**Comment by xfreebird** [comment]
You are too fast ! 😀 
I was blocked by #94 because I wasn't getting correct path values in some cases. In this case we'll need an additional input option, such as build log path. It will be useful for some people running jobs on remote build machines where multiple projects are being built at the same time.
The way it is now, building two projects with the same app and scheme name at the same time will overwrite the build log, we'll need to avoid path collisions too if used as it is.

I'll come later with a PR.

**Pull request merged**
