### PR TITLE
Check use_legacy_api instead of direct Xcode 7 check

### LINKED ISSUE #108: Invalid Swift Support - The SwiftSupport folder is missing
When building with fastlane/gym (latest version of both) on Xcode 7 GM, I'm getting an email with the following:

---

Dear developer,

We have discovered one or more issues with your recent delivery for APP NAME. To process your delivery, the following issues must be corrected:

Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team

---

For experimentation's sake, I switched back to my old manual build script (same exact setup except using manual scripts instead of fastlane) and was able to build without these errors – I suspect the old swift patches that were being applied to Xcode 6.x builds may still be necessary. This error appears to be distinct from #81

### PR DESCRIPTION
**Pull request by maxgoedjen**
Fixes #108

### CODE REVIEW

**Comment by KrauseFx** [comment]
Wow, how did I miss this... thanks for the pull request :+1:

**Comment by KrauseFx** [comment]
I added https://github.com/fastlane/gym/commit/921b94be0fd814df5cfb9235b6ee2c2b6ddae9eb to make your pull request work with Xcode 6 too.

**Comment by maxgoedjen** [comment]
Sometimes just takes a second set of eyes :eyes:. Thanks for the quick release!

**Comment by KrauseFx** [comment]
The new version is live already :rocket:

**Pull request merged**
