### PR TITLE
Updated gym to use the new xcodebuild API

### PR DESCRIPTION
**Pull request by KrauseFx**
Work in progress, you need to store
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>method</key>
    <string>app-store</string>
    <key>uploadSymbols</key>
    <true/>
    <key>uploadBitcode</key>
    <false/>
  </dict>
</plist>
```
in `/tmp/config.plist` to make this work. This of course will be generated by `gym` in the future.

Tests are not updated yet. 

### Installation
Clone the repo, switch to the `feature/switch-to-exportArchive` branch and run `sudo bundle install && sudo rake install` (remove `sudo` if you don't need it)

When testing, please upload the build to iTunes Connect and test if it works as expected.

Make sure you're using the latest Xcode Beta and set it using the `xcode-select` command.

### CODE REVIEW

**Comment by lacostej** [comment]
Tested with 6.4:
``````
xcodebuild: error: invalid option '-exportOptionsPlist'
INFO [2015-08-19 13:06:49.88]: Exit status: 64
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/gym-0.3.4/lib/gym/error_handler.rb:84:in `handle_package_error': Error packaging up the application (RuntimeError)
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/gym-0.3.4/lib/gym/runner.rb:77:in `block in package_app'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane_core-0.14.0/lib/fastlane_core/command_executor.rb:52:in `call'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane_core-0.14.0/lib/fastlane_core/command_executor.rb:52:in `execute'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/gym-0.3.4/lib/gym/runner.rb:73:in `package_app'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/gym-0.3.4/lib/gym/runner.rb:10:in `run'
``````

installing 7 beta 5 for testing

**Comment by KrauseFx** [comment]
@lacostej Did you set the path using `xcode-select`?

**Comment by lacostej** [comment]
@KrauseFx  :)
````
| Xcode path    | /Applications/Xcode6.4.app/Contents/Developer                                   |
````

I usually use DEVELOPER_DIR on most projects (which is taken into account with xcode-select -p and thus also with gym), but on that one I rely on the path set using xcode-select.

**Comment by lacostej** [comment]
And my project is currently not xcode7 compatible. 
``````
⌦  clang: error: linker command failed with exit code 1 (use -v to see invocation)
``````

**Comment by ellucianBret** [comment]
@KrauseFx FYI uploadBitcode will need to be true for most. Great work adding this.

This does need to only run against Xcode 7. Most will be moving to Xcode 7, but there maybe some who are staying with 6 for a while. It goes against the grain of Gym, but maybe you need a switch to turn off using the -exportOptionsPlist with xcodebuild? Or check the version of xcodebuild before building the command line.

**Comment by KrauseFx** [comment]
@ellucianBret yes, I'm thinking about maintaining both methods for now. Why does bitcode have to be on?

**Comment by ellucianBret** [comment]
From what I have read bitecode is required for WatchKit. Xcode archive defaults to bitecode on. It is not required, just the default

**Comment by pvegh** [comment]
I would be interested in trying this, because of issue #519. Could this be integrated into a version I can pull via Cocoapods, maybe enabling it explicitly with a parameter or so?

**Comment by KrauseFx** [comment]
@pvegh Sorry, not possible right now...

**Comment by lacostej** [comment]
@KrauseFx I can try integrating this into gym, and enabling it automatically (or based on an environment variable) for xcode 7 projects. WDYT ?

**Comment by KrauseFx** [comment]
Now that the Xcode GM is out it would make sense to work on it again. If you have some time @lacostej, feel free to dig into it. 

I'm currently working on the `deliver` upgrade to use `spaceship` :+1:

**Comment by KrauseFx** [comment]
Closing for https://github.com/fastlane/gym/pull/83

**Pull request closed without merging**
