### PR TITLE
Added support for `-derivedDataPath` and `-resultBundlePath` options.

### PR DESCRIPTION
**Pull request by bartoszj**
Hi,

Sometimes for Jenkins jobs I need to set derived data folder and/or set result bundle path. I've added additional options to handle `-derivedDataPath` and `-resultBundlePath`.

Also I've fixed some rubocop and rspec tests.

### CODE REVIEW

**Comment by CsabaSzabo** [comment]
+1 for these options

**Comment by KrauseFx** [comment]
Thanks, similar to https://github.com/fastlane/scan/pull/68, same comments apply to this PR :+1:

**Comment by bartoszj** [comment]
@KrauseFx. It should be OK now.

**Comment by KrauseFx** [comment]
Looks great, thanks for your contribution @bartoszj  :+1:

**Pull request merged**
