### PR TITLE
Shell escape product name in build command

### PR DESCRIPTION
**Pull request by HughJeffner**
Addressing issue #107 
Tested with single quote and brackets in product name

### CODE REVIEW

**Comment by HughJeffner** [comment]
I'm really not that familiar with ruby, do I need `require 'shellwords'`?  I think my change may have only worked since `package_command_generator.rb` may have already loaded it first.

**Comment by KrauseFx** [comment]
The `require` is fine. Sorry, but I think I caused a merge conflict. Could you resolve it and squash your commits into one?

**Comment by KrauseFx** [comment]
Have you tested this change locally?

**Comment by HughJeffner** [comment]
Yeah I just did a `rake install` and tested manually, is there a preferred way of testing?

**Comment by KrauseFx** [comment]
Perfect, thanks for your contribution @HughJeffner, this will be in the next release :+1:

**Pull request merged**
