### PR TITLE
Defines prefix in a separate method for PackageCommandGenerators

### PR DESCRIPTION
**Pull request by natanrolnik**
To be consistent with [BuildCommandGenerator](https://github.com/fastlane/gym/blob/master/lib/gym/generators/build_command_generator.rb#L5-L18)

### CODE REVIEW

**Comment by lacostej** [comment]
As a side note, this will conflict with #176

**Comment by natanrolnik** [comment]
Indeed =/

**Comment by KrauseFx** [comment]
Sorry @natanrolnik, but yeah, this conflicts now. Could you update the PR?

**Comment by natanrolnik** [comment]
I will do it in the next few days @KrauseFx !

**Comment by KrauseFx** [comment]
Thanks @natanrolnik :+1:

**Comment by mpirri** [comment]
@natanrolnik I am sorry to have to do this, but we are moving this weekend to a new, unified fastlane mono repo. Since this PR is not currently in a state to be merged, I need to close it. Please feel free to open a new PR on the new repo after Monday if you are still interested in contributing this to `gym`. Let us know if you need any assistance with this process.

**Comment by natanrolnik** [comment]
No problem, @mpirri !

**Pull request closed without merging**
